
debug:           false
db:
  username:     "root"
  userpassword: "root"
  host:         "localhost"
  port:         "3306"
  database:     "go_uchit_go"
host:
  ip:           "localhost"
  port:         "5000"